### ISSUE TITLE
icons and font-awesome 6

### ISSUE THREAD

**Issue by richarvey** [sbruder/spectral#20]
Is there an easy way to migrate to font-awesome 6?

I tried a direct swap and the tried adding fa-regular or fa-brands where needed but if I include .icon in the class the icon fails to load.

Cheers Ric

**Comment by dholbach** [comment]
Thanks a lot for looking into this!

Do you think you could share a branch with your approach somewhere?

**Comment by richarvey** [comment]
I have it working and have submitted a pull request.
